baseurl = "/"
title = "Andrew Geisler"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
# disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier="experience"
    name = "Experience"
    url  = "/experience/"
    weight = 2
[[menu.main]]
    identifier="education"
    name = "Education"
    url  = "/education/"
    weight = 3

[[menu.main]]
    identifier = "Examples"
    name = "Examples"
    url  = "/examples/"
    weight = 4

[[menu.main]]
    identifier = "Music"
    name = "Music"
    url  = "/Music/"
    weight = 4

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/andrewgeisler"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "LinkedIn"
    url = "http://www.linkedin.com/in/andrewjgeisler/"
    pre = "<i class='fab fa-2x fa-linkedin'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com/_andrewgeisler"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:andrew.geisler@email.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devows", "hugo", "go"]
    mainSections = ["blog"]
    defaultDescription = "Site template made by devcows using hugo"
    default_sharing_image = "img/sharing-default.png"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "violet"

    about_us = "<p>Passionate data professional seeking continued growth and community in all things R,  stats, modeling, and data analysis.</p>"
    
    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/ag-logo.png"
    logo_small = "img/ag-logo-small.png"
    #address = """<p class="text-uppercase"><strong>Old Hickory, Tennessee</strong></p>"""


# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">
        <a href="https://github.com/andrewgeisler/andrew-geisler-portfolio">Created with RBlogdown</a></p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true

[params.features]
    enable = true
